spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/order_db
    username: ${DB_USERNAME:lykuong}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

jwt:
  claim: SYSTEM
  secret: verySecretKeyChangeInProductionVerySecretKeyChangeInProduction

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://gateway:8080}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://gateway:8080}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://gateway:8080}

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
    instances:
      orderRetry:
        base-config: default
