spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: lykuong
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

jwt:
  secret: verySecretKeyChangeInProductionVerySecretKeyChangeInProduction

server:
  port: 8082
