spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: internal
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/internal/**

        - id: payment
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/products,/products/**,/categories,/categories/**

        - id: cart
          uri: lb://CART
          predicates:
            - Path=/cart,/cart/**

        - id: inventory
          uri: lb://INVENTORY
          predicates:
            - Path=/inventory,/inventory/**
server:
  port: ${SERVER_PORT:0}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
