server:
  port: 8083

spring:
  application:
    name: RECOVERY-SERVICE

logging:
  level:
    root: INFO
    com.kuong.recovery: DEBUG

recovery:
  order-service:
    base-url: http://localhost:8082
  schedule:
    fixed-delay: 60000
jwt:
  secret: verySecretKeyChangeInProductionVerySecretKeyChangeInProduction

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
    instances:
      orderRecoverable:
        base-config: default
      orderRetry:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
    instances:
      orderRecoverable:
        base-config: default
      orderRetry:
        base-config: default
